# Generated by Django 3.2.7 on 2021-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('pack', models.BigIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_id', models.IntegerField(default=1)),
                ('buyer_card', models.BigIntegerField(default=1111111111111111)),
                ('buyer_card_name', models.CharField(max_length=50)),
                ('buyer_card_due_date', models.DateField()),
                ('buyer_card_cvv', models.IntegerField(default=111)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
