# Generated by Django 3.2.7 on 2021-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pack',
            field=models.CharField(max_length=50),
        ),
    ]
