query Query($purchaseId: Int!) {
  purchase(purchaseId: $purchaseId) {
    id
    total
    buyer_id
    buyer_card
    buyer_card_name
    buyer_card_due_date
    buyer_card_cvv
    created_at
    user {
      id
      username
      email
      first_name
      last_name
      is_admin
      country
      birth_day
    }
    pack {
      _id
      title
      description
      price
      isActive
      discount
      country
      imageUrl
      createdAt
      modifiedAt
    }
  }
}
